version: '3.8'

services:
  python_ai:
    build: .
    container_name: python_ai_container
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/app/notebooks
    environment:
      MYSQL_HOST: mysql_server
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
      MONGODB_URI: mongodb://mongo_server:27017
    depends_on:
      - mysql_server
      - mongo_server

  mysql_server:
    image: mysql:8.0
    container_name: mysql_ai_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  mongo_server:
    image: mongo:7.0
    container_name: mongo_ai_container
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
