services:
  python_ai:
    build: .
    container_name: python_ai_container
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/app/notebooks
    environment:
      MYSQL_HOST: mysql_server
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
      MONGODB_URI: mongodb://mongo_server:27017
      SPARK_MASTER: spark://spark_hadoop:7077
    depends_on:
      - mysql_server
      - mongo_server
      - spark_master

  mysql_server:
    image: mysql:8.0
    container_name: mysql_ai_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  mongo_server:
    image: mongo:7.0
    container_name: mongo_ai_container
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  spark_master:
    image: bitnami/spark:3.4.1
    container_name: spark_hadoop_container
    hostname: spark_hadoop
    environment:
      - ENABLE_INIT_DAEMON=false
      - SPARK_MASTER_HOST=spark_hadoop
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - 8080:8080
      - 7077:7077

  spark_worker:
    image: bitnami/spark:3.4.1
    container_name: spark_worker_container
    environment:
      - SPARK_MASTER=spark://spark_hadoop:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    depends_on:
      - spark_master

volumes:
  mysql_data:
  mongo_data:

networks:
  sparknet: